title: Clash免费节点
description: 最新免费 Clash/VPN/V2ray节点分享
baseurl: ""
url: "http://localhost:4000"

# 构建设置
markdown: kramdown
permalink: pretty

# 集合
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title.html

# 默认值
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Clash节点"

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore

# 分页设置
paginate: 10
paginate_path: "/page:num/"

# 导航菜单
navigation:
  - title: 首页
    url: /
  - title: 免费节点
    url: /nodes/
  - title: 推荐机场
    url: /recommendations/
  - title: 新闻资讯
    url: /news/
  - title: 客户端
    url: /clients/ 